### ISSUE TITLE
Проблема с деплоем

### ISSUE THREAD

**Issue by dracowf** [bevis-ui/bevis-blog#3]
Честно пытался, но не получается всё никак.
http://i.gyazo.com/b0dd4f58a4e5191adfa3620a1525f79f.png
Не совсем понимаю почему стучится на репозиторий bevis-ui.

**Comment by makishvili** [comment]
Это какую команду вы выполняете в терминале?
И если не сложно, сделайте скриншот всего ответа - вместе с запускаемой командой.

**Comment by makishvili** [comment]
Вы создавали свой репозиторий? Как тут написано?
https://github.com/bevis-ui/bevis-blog#Как-выложить-на-бесплатный-хостинг

**Comment by dracowf** [comment]
1) make deploy
2) Да, создал.
https://github.com/dracowf/blog
И сходил по ссылке https://pages.github.com, где было сказано создать ещё репозиторий равный своему нику: https://github.com/dracowf/dracowf
http://i.gyazo.com/fe6bf0e989a2709082d28b7811bf8c80.gif
http://i.gyazo.com/9d2c555d13855911a769a4805d93b43e.png
http://i.gyazo.com/4d831aed07dda0a463ca0f3ad7539bdd.png

**Comment by makishvili** [comment]
Я постараюсь воспроизвести и напишу вам.

**Comment by dracowf** [comment]
По-моему это связано с ключами безопасности:
https://help.github.com/articles/error-permission-to-user-repo-denied-to-user-other-repo/

**Comment by makishvili** [comment]
Моя вина.
Проблему решил, коммит: https://github.com/bevis-ui/bevis-blog/commit/225885bf1f423968e5650b84bd979deb85ca9fec
Документацию обновил, коммит: https://github.com/bevis-ui/bevis-blog/commit/74ae6322928c2fea9a5fdeef9af8a4f44a62be1e

Теперь, как мы исправим у вас. Вообще-то это будет не исправление, а создание заново. Так можно? 
1. Удалите репозиторий https://github.com/dracowf/blog. То есть вообще.
2. Склонируйте заново болванку блога - как описано в разделе https://github.com/bevis-ui/bevis-blog#Быстрое-знакомство
3. Заведите пустой репозиторий https://github.com/dracowf/blog. Не инициализируйте его! Просто создайте и переходите к следующему шагу.
4. Выполните три гитовых команды из этой инструкции: https://github.com/bevis-ui/bevis-blog#Как-выложить-на-бесплатный-хостинг
5. Теперь можно делать `make deploy`

**Comment by dracowf** [comment]
Заработало! ^_^
http://dracowf.github.io/last-chance
Я был близок, но всё же не туда свернул: http://i.gyazo.com/232bbbff429fd0e3b3dbb8f95fa8489a.png =)

**Comment by makishvili** [comment]
Ура!
То есть вы справились и без моих наставлений?
Или я смог вовремя исправить свою ошибку? :)

**Comment by makishvili** [comment]
Спасибо вам за багрепорт, Адександр.
Закрываем?

**Comment by dracowf** [comment]
Я млин вам вместо коммитов, только головную боль обеспечиваю =( Закрываем!)
Не - ваше решение было 100%
А я в итоге не дошёл до решения =)
